package main

import (
	"log"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/cors"
	"github.com/gofiber/fiber/v2/middleware/logger"
	"github.com/gofiber/swagger"               // swagger handler
	_ "github.com/oopbest/go-pos-backend/docs" // docs generated by Swag CLI
	"github.com/oopbest/go-pos-backend/internal/config"
	"github.com/oopbest/go-pos-backend/internal/database"
	"github.com/oopbest/go-pos-backend/internal/handlers"
)

// @title         Restaurant & Cafe POS API
// @version       1.0
// @description   POS Backend API for Restaurant and Cafe with Table & Kitchen Management
// @host          localhost:8080
// @BasePath      /
func main() {
	cfg := config.LoadConfig()
	database.ConnectDB(cfg)

	app := fiber.New()

	app.Use(logger.New())
	app.Use(cors.New())

	// Health Check
	app.Get("/health", func(c *fiber.Ctx) error {
		return c.JSON(fiber.Map{
			"status":  "ok",
			"message": "Restaurant POS Backend is connected to PostgreSQL!",
		})
	})

	// Swagger Route
	app.Get("/swagger/*", swagger.HandlerDefault)

	// API Routes Group
	api := app.Group("/api")

	// Table Routes
	api.Get("/tables", handlers.GetTables)
	api.Get("/tables/:id", handlers.GetTableByID)
	api.Put("/tables/:id/status", handlers.UpdateTableStatus)

	// Menu & Category Routes
	api.Get("/categories", handlers.GetCategories)
	api.Get("/products", handlers.GetProducts)

	// Order Routes
	api.Post("/orders", handlers.CreateOrder)
	api.Get("/orders/table/:table_id", handlers.GetActiveOrderByTableID)
	api.Post("/orders/:id/items", handlers.AddItemsToOrder)
	api.Post("/orders/:id/checkout", handlers.CheckoutOrder)

	// Kitchen Routes
	api.Get("/kitchen/items", handlers.GetKitchenItems)
	api.Put("/kitchen/items/:id/status", handlers.UpdateItemKitchenStatus)

	log.Printf("Server starting on port %s...", cfg.Port)
	log.Printf("Swagger UI available at http://localhost:%s/swagger/", cfg.Port)
	log.Fatal(app.Listen(":" + cfg.Port))
}
