// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/categories": {
            "get": {
                "description": "ดึงหมวดหมู่ทั้งหมด",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Menu"
                ],
                "summary": "Get all categories",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Category"
                            }
                        }
                    }
                }
            }
        },
        "/api/orders": {
            "post": {
                "description": "เปิดโต๊ะและสั่งรายการอาหารครั้งแรก",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "Create order / Open table",
                "parameters": [
                    {
                        "description": "Order Payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateOrderRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Order"
                        }
                    }
                }
            }
        },
        "/api/orders/table/{table_id}": {
            "get": {
                "description": "ดึงบิลปัจจุบันที่ยังเปิดอยู่ของโต๊ะนั้น",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "Get active order by table",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Table ID",
                        "name": "table_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Order"
                        }
                    }
                }
            }
        },
        "/api/products": {
            "get": {
                "description": "ดึงเมนูทั้งหมด (กรองตาม category_id หรือ station ได้)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Menu"
                ],
                "summary": "Get all products",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Category ID",
                        "name": "category_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Station (kitchen or bar)",
                        "name": "station",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Product"
                            }
                        }
                    }
                }
            }
        },
        "/api/tables": {
            "get": {
                "description": "ดึงรายชื่อโต๊ะทั้งหมด",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tables"
                ],
                "summary": "Get all tables",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Table"
                            }
                        }
                    }
                }
            }
        },
        "/api/tables/{id}": {
            "get": {
                "description": "ดึงข้อมูลโต๊ะเดี่ยวๆ ตาม ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tables"
                ],
                "summary": "Get table by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Table ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Table"
                        }
                    }
                }
            }
        },
        "/api/tables/{id}/status": {
            "put": {
                "description": "อัปเดตสถานะโต๊ะ (available, occupied, reserved)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tables"
                ],
                "summary": "Update table status",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Table ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Status Payload (e.g. {\\",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Table"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.CreateOrderItemRequest": {
            "type": "object",
            "properties": {
                "product_id": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer"
                },
                "special_instructions": {
                    "type": "string"
                }
            }
        },
        "handlers.CreateOrderRequest": {
            "type": "object",
            "properties": {
                "customer_count": {
                    "type": "integer"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.CreateOrderItemRequest"
                    }
                },
                "table_id": {
                    "type": "integer"
                }
            }
        },
        "models.Category": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "default_station": {
                    "$ref": "#/definitions/models.StationType"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "description": "e.g. \"อาหารจานเดียว\", \"กาแฟ\", \"ของหวาน\"",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.ItemKitchenStatus": {
            "type": "string",
            "enum": [
                "pending",
                "cooking",
                "ready",
                "served"
            ],
            "x-enum-comments": {
                "ItemCooking": "ครัวกำลังปรุง",
                "ItemPending": "เพิ่งสั่ง ยังไม่เริ่มทำ",
                "ItemReady": "ทำเสร็จ รอเสิร์ฟ",
                "ItemServed": "เสิร์ฟแล้ว"
            },
            "x-enum-descriptions": [
                "เพิ่งสั่ง ยังไม่เริ่มทำ",
                "ครัวกำลังปรุง",
                "ทำเสร็จ รอเสิร์ฟ",
                "เสิร์ฟแล้ว"
            ],
            "x-enum-varnames": [
                "ItemPending",
                "ItemCooking",
                "ItemReady",
                "ItemServed"
            ]
        },
        "models.Order": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "customer_count": {
                    "type": "integer"
                },
                "discount": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.OrderItem"
                    }
                },
                "order_no": {
                    "description": "e.g. \"ORD-20260920-001\"",
                    "type": "string"
                },
                "paid_at": {
                    "type": "string"
                },
                "payment_method": {
                    "description": "\"cash\", \"promptpay\", \"credit_card\"",
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/models.OrderStatus"
                },
                "subtotal": {
                    "type": "number"
                },
                "table": {
                    "$ref": "#/definitions/models.Table"
                },
                "table_id": {
                    "type": "integer"
                },
                "tax": {
                    "type": "number"
                },
                "total_amount": {
                    "type": "number"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.OrderItem": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "kitchen_status": {
                    "$ref": "#/definitions/models.ItemKitchenStatus"
                },
                "order_id": {
                    "type": "integer"
                },
                "product": {
                    "$ref": "#/definitions/models.Product"
                },
                "product_id": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer"
                },
                "special_instructions": {
                    "description": "e.g. \"ไม่หวาน, แยกน้ำแข็ง\"",
                    "type": "string"
                },
                "station": {
                    "$ref": "#/definitions/models.StationType"
                },
                "subtotal": {
                    "type": "number"
                },
                "unit_price": {
                    "type": "number"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.OrderStatus": {
            "type": "string",
            "enum": [
                "open",
                "completed",
                "cancelled"
            ],
            "x-enum-comments": {
                "OrderCancelled": "ยกเลิก",
                "OrderCompleted": "เช็คบิลแล้ว",
                "OrderOpen": "กำลังทาน ยังไม่เช็คบิล"
            },
            "x-enum-descriptions": [
                "กำลังทาน ยังไม่เช็คบิล",
                "เช็คบิลแล้ว",
                "ยกเลิก"
            ],
            "x-enum-varnames": [
                "OrderOpen",
                "OrderCompleted",
                "OrderCancelled"
            ]
        },
        "models.Product": {
            "type": "object",
            "properties": {
                "category": {
                    "$ref": "#/definitions/models.Category"
                },
                "category_id": {
                    "type": "integer"
                },
                "cost": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image_url": {
                    "type": "string"
                },
                "is_available": {
                    "description": "สต็อกหมดหรือไม่",
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "station": {
                    "$ref": "#/definitions/models.StationType"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.StationType": {
            "type": "string",
            "enum": [
                "kitchen",
                "bar"
            ],
            "x-enum-comments": {
                "StationBar": "บาร์น้ำ/กาแฟ",
                "StationKitchen": "ครัวอาหาร"
            },
            "x-enum-descriptions": [
                "ครัวอาหาร",
                "บาร์น้ำ/กาแฟ"
            ],
            "x-enum-varnames": [
                "StationKitchen",
                "StationBar"
            ]
        },
        "models.Table": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "seat_capacity": {
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/models.TableStatus"
                },
                "table_no": {
                    "description": "e.g. \"T-01\", \"A1\"",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "zone": {
                    "description": "e.g. \"Indoor\", \"Outdoor\", \"Bar\"",
                    "type": "string"
                }
            }
        },
        "models.TableStatus": {
            "type": "string",
            "enum": [
                "available",
                "occupied",
                "reserved"
            ],
            "x-enum-comments": {
                "TableAvailable": "โต๊ะว่าง",
                "TableOccupied": "มีลูกค้านั่ง",
                "TableReserved": "จองไว้"
            },
            "x-enum-descriptions": [
                "โต๊ะว่าง",
                "มีลูกค้านั่ง",
                "จองไว้"
            ],
            "x-enum-varnames": [
                "TableAvailable",
                "TableOccupied",
                "TableReserved"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Restaurant & Cafe POS API",
	Description:      "POS Backend API for Restaurant and Cafe with Table & Kitchen Management",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
